#!/usr/bin/env bash
# PreToolUse(Edit|Write): keep secrets, lockfiles and git internals out of the editor tools.
set -euo pipefail
FILE=$(jq -r '.tool_input.file_path // empty')
[[ -z "$FILE" ]] && exit 0
base=$(basename "$FILE")
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
case "$FILE" in
  */.git/*|.git/*) block "$FILE is inside .git" ;;
esac
case "$base" in
  *.example) exit 0 ;;
  .env|.env.*|overlay.env) block "$base holds secrets; edit it by hand, never through the agent" ;;
  package-lock.json|pnpm-lock.yaml|yarn.lock)
    block "lockfiles are regenerated by the package manager, not edited" ;;
esac
exit 0
